/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as DebtsRouteImport } from './routes/debts'
import { Route as QuantitiesRouteImport } from './routes/quantities'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'
import { Route as SuppliersIndexRouteImport } from './routes/suppliers.index'
import { Route as SuppliersIdRouteImport } from './routes/suppliers.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DebtsRoute = DebtsRouteImport.update({
  id: '/debts',
  path: '/debts',
  getParentRoute: () => rootRouteImport,
} as any)
const QuantitiesRoute = QuantitiesRouteImport.update({
  id: '/quantities',
  path: '/quantities',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIndexRoute = SuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIdRoute = SuppliersIdRouteImport.update({
  id: '/suppliers/$id',
  path: '/suppliers/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/debts': typeof DebtsRoute
  '/quantities': typeof QuantitiesRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/vault': typeof VaultRoute
  '/customers/$id': typeof CustomersIdRoute
  '/suppliers/$id': typeof SuppliersIdRoute
  '/customers/': typeof CustomersIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/debts': typeof DebtsRoute
  '/quantities': typeof QuantitiesRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/vault': typeof VaultRoute
  '/customers/$id': typeof CustomersIdRoute
  '/suppliers/$id': typeof SuppliersIdRoute
  '/customers': typeof CustomersIndexRoute
  '/suppliers': typeof SuppliersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/debts': typeof DebtsRoute
  '/quantities': typeof QuantitiesRoute
  '/settings': typeof SettingsRoute
  '/transactions': typeof TransactionsRoute
  '/vault': typeof VaultRoute
  '/customers/$id': typeof CustomersIdRoute
  '/suppliers/$id': typeof SuppliersIdRoute
  '/customers/': typeof CustomersIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/debts'
    | '/quantities'
    | '/settings'
    | '/transactions'
    | '/vault'
    | '/customers/$id'
    | '/suppliers/$id'
    | '/customers/'
    | '/suppliers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/debts'
    | '/quantities'
    | '/settings'
    | '/transactions'
    | '/vault'
    | '/customers/$id'
    | '/suppliers/$id'
    | '/customers'
    | '/suppliers'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/debts'
    | '/quantities'
    | '/settings'
    | '/transactions'
    | '/vault'
    | '/customers/$id'
    | '/suppliers/$id'
    | '/customers/'
    | '/suppliers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DebtsRoute: typeof DebtsRoute
  QuantitiesRoute: typeof QuantitiesRoute
  SettingsRoute: typeof SettingsRoute
  TransactionsRoute: typeof TransactionsRoute
  VaultRoute: typeof VaultRoute
  CustomersIdRoute: typeof CustomersIdRoute
  SuppliersIdRoute: typeof SuppliersIdRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  SuppliersIndexRoute: typeof SuppliersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debts': {
      id: '/debts'
      path: '/debts'
      fullPath: '/debts'
      preLoaderRoute: typeof DebtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quantities': {
      id: '/quantities'
      path: '/quantities'
      fullPath: '/quantities'
      preLoaderRoute: typeof QuantitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/': {
      id: '/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof SuppliersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/$id': {
      id: '/suppliers/$id'
      path: '/suppliers/$id'
      fullPath: '/suppliers/$id'
      preLoaderRoute: typeof SuppliersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DebtsRoute: DebtsRoute,
  QuantitiesRoute: QuantitiesRoute,
  SettingsRoute: SettingsRoute,
  TransactionsRoute: TransactionsRoute,
  VaultRoute: VaultRoute,
  CustomersIdRoute: CustomersIdRoute,
  SuppliersIdRoute: SuppliersIdRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  SuppliersIndexRoute: SuppliersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
